# Generated by Django 5.1 on 2024-10-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60)),
                ('Representante', models.CharField(max_length=80)),
                ('Contacto', models.CharField(max_length=14)),
            ],
        ),
    ]
