# Generated by Django 5.1.1 on 2024-11-04 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_proveedor_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='estado',
            new_name='habilitado',
        ),
    ]
