# Generated by Django 5.1.1 on 2024-11-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_estado_proveedor_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
