# Generated by Django 5.1 on 2024-11-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_compra_habilitado_compra_proveedor_and_more'),
        ('App', '0006_empleado_habilitado'),
    ]

    operations = [
    ]
