# Generated by Django 5.1 on 2024-11-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_producto_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalles', models.TextField()),
                ('tipo', models.CharField(default='venta', max_length=50)),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo',
            field=models.CharField(default='compra', max_length=50),
        ),
    ]
