# Generated by Django 5.1.1 on 2024-11-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_venta_compra_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
